"""Subdivision **design** tool — lay out lots inside a parent tract.

The neighbouring :mod:`meridian.jurisdictions.subdivision` module *parses*
a recorded plat description ("Lot 12, Block A of Travis Heights…"). This
module does the inverse: given a parent polygon and a design specification
(min lot area, frontage, depth, setbacks, street ROW width), it lays out
geometric lots and streets, validates them against the spec, and exports
the result as a :class:`~meridian.jurisdictions.fabric.ParcelFabric` ready
to be merged into the project topology.

v0 covers the two layouts that account for the vast majority of suburban
subdivisions:

* **Strip** — a single row of lots facing one street along one side of
  a rectangular parent.
* **Rectangular grid** — two rows of lots back-to-back across a central
  through-street running along the long axis of the parent. The lots
  share rear lot lines (which become a single shared edge in the fabric).

Deferred to a future iteration:

* Irregular parents (Voronoi / medial-axis / pie-slice cul-de-sacs).
* Curved streets and cul-de-sac bulbs.
* Variable lot sizes per row (you can call ``design_strip`` repeatedly to
  approximate this today).
* Storm-water tracts, common-area sizing rules, traffic-impact analysis.

Even at v0 this is enough to run a "what fits on this 5-acre rectangle?"
sanity check, generate the lot-line geometry, and feed it into the parcel
fabric so subsequent edits ripple through neighbours correctly.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from enum import Enum

from meridian.domain.geometry import BBox2D, Point2D, Polygon
from meridian.jurisdictions.fabric import ParcelFabric

# ── Specs ───────────────────────────────────────────────────────────────────


class LayoutKind(str, Enum):
    STRIP = "strip"
    RECTANGULAR_GRID = "rectangular_grid"


@dataclass(frozen=True, slots=True)
class LotSpec:
    """The minimum dimensions every designed lot must satisfy.

    All distances are in the units of the parent polygon's CRS (typically
    feet for US State Plane, metres for UTM). Areas are in those units²
    (sq ft, m²).

    The setbacks define the *building envelope* and are reported but do not
    by themselves change the lot polygon — front/side/rear setbacks cut into
    the lot, not the parcel boundary.
    """

    min_area: float
    min_frontage: float
    min_depth: float
    setback_front: float = 0.0
    setback_rear: float = 0.0
    setback_side: float = 0.0
    max_depth_to_frontage_ratio: float | None = None  # e.g. 3.0 — long, narrow lots disallowed

    def __post_init__(self) -> None:
        for name, v in (
            ("min_area", self.min_area),
            ("min_frontage", self.min_frontage),
            ("min_depth", self.min_depth),
        ):
            if v <= 0:
                raise ValueError(f"{name} must be positive, got {v}.")
        for name, v in (
            ("setback_front", self.setback_front),
            ("setback_rear", self.setback_rear),
            ("setback_side", self.setback_side),
        ):
            if v < 0:
                raise ValueError(f"{name} must be >= 0, got {v}.")
        if (
            self.max_depth_to_frontage_ratio is not None
            and self.max_depth_to_frontage_ratio <= 0
        ):
            raise ValueError("max_depth_to_frontage_ratio must be > 0 if set.")


@dataclass(frozen=True, slots=True)
class StreetSpec:
    """Right-of-way dimensions for a designed street."""

    row_width: float          # full ROW (curb-to-curb + planter strips + sidewalks)
    name: str | None = None

    def __post_init__(self) -> None:
        if self.row_width <= 0:
            raise ValueError("row_width must be positive.")


# ── Designed entities ───────────────────────────────────────────────────────


@dataclass(frozen=True, slots=True)
class DesignedLot:
    """A single lot generated by the design tool."""

    number: str
    block: str
    polygon: Polygon
    frontage_length: float
    depth_length: float
    front_edge: tuple[Point2D, Point2D]   # the edge facing the street
    setbacks: LotSpec                     # echoed from the spec for downstream tools

    @property
    def area(self) -> float:
        return self.polygon.area()


@dataclass(frozen=True, slots=True)
class DesignedStreet:
    """A street ROW polygon plus its centreline."""

    name: str
    polygon: Polygon
    centerline_start: Point2D
    centerline_end: Point2D
    row_width: float

    @property
    def length(self) -> float:
        return math.hypot(
            self.centerline_end.x - self.centerline_start.x,
            self.centerline_end.y - self.centerline_start.y,
        )


@dataclass(frozen=True, slots=True)
class SubdivisionDesign:
    """The output of a design run."""

    name: str
    layout: LayoutKind
    parent: Polygon
    lots: tuple[DesignedLot, ...]
    streets: tuple[DesignedStreet, ...]
    spec: LotSpec
    notes: tuple[str, ...] = ()
    extra: dict[str, str] = field(default_factory=dict)

    @property
    def total_lot_area(self) -> float:
        return sum(lot.area for lot in self.lots)

    @property
    def total_street_area(self) -> float:
        return sum(s.polygon.area() for s in self.streets)

    @property
    def density_lots_per_unit_area(self) -> float:
        a = self.parent.area()
        return len(self.lots) / a if a > 0 else 0.0


# ── Validation ──────────────────────────────────────────────────────────────


@dataclass(frozen=True, slots=True)
class DesignIssue:
    severity: str          # "error" | "warning"
    lot_number: str | None
    message: str


def validate_design(
    design: SubdivisionDesign, *, spec: LotSpec | None = None
) -> tuple[DesignIssue, ...]:
    """Re-check every lot against a spec.

    If ``spec`` is omitted, ``design.spec`` is used (re-validation).
    """
    target = spec or design.spec
    issues: list[DesignIssue] = []
    for lot in design.lots:
        if lot.area < target.min_area - 1e-6:
            issues.append(
                DesignIssue(
                    severity="error",
                    lot_number=lot.number,
                    message=(
                        f"Lot {lot.number} area {lot.area:.1f} < required "
                        f"min_area {target.min_area:.1f}."
                    ),
                )
            )
        if lot.frontage_length < target.min_frontage - 1e-6:
            issues.append(
                DesignIssue(
                    severity="error",
                    lot_number=lot.number,
                    message=(
                        f"Lot {lot.number} frontage {lot.frontage_length:.1f} < "
                        f"required min_frontage {target.min_frontage:.1f}."
                    ),
                )
            )
        if lot.depth_length < target.min_depth - 1e-6:
            issues.append(
                DesignIssue(
                    severity="error",
                    lot_number=lot.number,
                    message=(
                        f"Lot {lot.number} depth {lot.depth_length:.1f} < "
                        f"required min_depth {target.min_depth:.1f}."
                    ),
                )
            )
        # Building envelope must be non-zero after applying setbacks.
        envelope_w = lot.frontage_length - 2 * target.setback_side
        envelope_d = lot.depth_length - target.setback_front - target.setback_rear
        if envelope_w <= 0 or envelope_d <= 0:
            issues.append(
                DesignIssue(
                    severity="error",
                    lot_number=lot.number,
                    message=(
                        f"Lot {lot.number} has no buildable envelope after "
                        f"setbacks (envelope {envelope_w:.1f} × {envelope_d:.1f})."
                    ),
                )
            )
        if target.max_depth_to_frontage_ratio is not None:
            ratio = lot.depth_length / lot.frontage_length if lot.frontage_length > 0 else float("inf")
            if ratio > target.max_depth_to_frontage_ratio + 1e-6:
                issues.append(
                    DesignIssue(
                        severity="warning",
                        lot_number=lot.number,
                        message=(
                            f"Lot {lot.number} depth/frontage ratio {ratio:.2f} "
                            f"exceeds {target.max_depth_to_frontage_ratio}; "
                            "client may want to subdivide differently."
                        ),
                    )
                )
    return tuple(issues)


# ── Buildable-envelope helper ───────────────────────────────────────────────


def buildable_envelope(lot: DesignedLot) -> Polygon:
    """Return the building envelope (lot minus setbacks) as a polygon.

    The lot is assumed axis-aligned (true for v0 layouts). The envelope is
    the lot bounding-box shrunk by the front/rear/side setbacks; if any
    setback exceeds the corresponding lot dimension, a ``ValueError`` is
    raised (the lot has no buildable area; ``validate_design`` catches this
    and emits an error rather than raising).
    """
    s = lot.setbacks
    # Compute the lot's axis-aligned envelope by projecting the front edge to
    # determine "facing direction" — front_edge is along the street.
    fx1, fy1 = lot.front_edge[0].x, lot.front_edge[0].y
    _fx2, fy2 = lot.front_edge[1].x, lot.front_edge[1].y
    # Determine if front edge is horizontal or vertical (v0 grid is axis-aligned).
    bbox = lot.polygon.bbox()
    if abs(fy1 - fy2) < 1e-6:
        # front edge is horizontal → setback_front pushes "up" or "down"
        # depending on whether front edge is at the bottom or top of the bbox.
        front_is_bottom = abs(fy1 - bbox.min_y) < abs(fy1 - bbox.max_y)
        ymin = bbox.min_y + (s.setback_front if front_is_bottom else s.setback_rear)
        ymax = bbox.max_y - (s.setback_rear if front_is_bottom else s.setback_front)
        xmin = bbox.min_x + s.setback_side
        xmax = bbox.max_x - s.setback_side
    else:
        # front edge is vertical
        front_is_left = abs(fx1 - bbox.min_x) < abs(fx1 - bbox.max_x)
        xmin = bbox.min_x + (s.setback_front if front_is_left else s.setback_rear)
        xmax = bbox.max_x - (s.setback_rear if front_is_left else s.setback_front)
        ymin = bbox.min_y + s.setback_side
        ymax = bbox.max_y - s.setback_side
    if xmax <= xmin or ymax <= ymin:
        raise ValueError(f"Lot {lot.number} has no buildable envelope after setbacks.")
    crs = lot.polygon.crs
    ring = (
        Point2D(x=xmin, y=ymin, crs=crs),
        Point2D(x=xmax, y=ymin, crs=crs),
        Point2D(x=xmax, y=ymax, crs=crs),
        Point2D(x=xmin, y=ymax, crs=crs),
        Point2D(x=xmin, y=ymin, crs=crs),
    )
    return Polygon(exterior=ring)


# ── Layout: strip ───────────────────────────────────────────────────────────


def design_strip(
    parent: Polygon,
    lot_spec: LotSpec,
    *,
    name: str = "Strip Subdivision",
    block: str = "A",
    frontage_side: str = "south",   # "north" / "south" / "east" / "west"
    target_lots: int | None = None,
) -> SubdivisionDesign:
    """Lay out a single row of lots facing one side of a rectangular parent.

    The parent must be (approximately) an axis-aligned rectangle; the parent's
    bbox is used for layout. Lots are tiled along ``frontage_side`` at the
    smallest frontage that satisfies ``lot_spec.min_frontage``; each lot's
    depth runs the full perpendicular dimension of the parent.

    If ``target_lots`` is given, the function tries to widen each lot evenly
    to fit exactly that many across; if that violates ``min_frontage`` it
    raises.
    """
    bbox = parent.bbox()
    width, height = bbox.width, bbox.height

    # frontage_axis = width if N/S facing, height if E/W facing
    front_horizontal = frontage_side in ("north", "south")
    frontage_axis = width if front_horizontal else height
    depth_axis = height if front_horizontal else width

    if depth_axis < lot_spec.min_depth:
        raise ValueError(
            f"Parent depth {depth_axis:.1f} < lot_spec.min_depth {lot_spec.min_depth:.1f}."
        )

    if target_lots is None:
        # Start at the max that fits by frontage, then reduce until each
        # lot's area also clears min_area. This is the "best fit" the user
        # gets when they don't pin a count.
        target_lots = max(1, math.floor(frontage_axis / lot_spec.min_frontage))
        while target_lots > 1 and (frontage_axis / target_lots) * depth_axis < lot_spec.min_area:
            target_lots -= 1

    lot_frontage = frontage_axis / target_lots
    if lot_frontage < lot_spec.min_frontage:
        raise ValueError(
            f"Cannot fit {target_lots} lots along frontage {frontage_axis:.1f} — "
            f"per-lot frontage {lot_frontage:.1f} < min {lot_spec.min_frontage:.1f}."
        )
    if lot_frontage * depth_axis < lot_spec.min_area:
        raise ValueError(
            f"Lot would be {lot_frontage:.1f}×{depth_axis:.1f} = "
            f"{lot_frontage * depth_axis:.1f} < min_area {lot_spec.min_area:.1f}."
        )

    lots = tuple(
        _build_lot(
            number=str(i + 1),
            block=block,
            bbox=bbox,
            frontage_horizontal=front_horizontal,
            i=i,
            n=target_lots,
            frontage_side=frontage_side,
            lot_spec=lot_spec,
        )
        for i in range(target_lots)
    )
    notes: list[str] = []
    if target_lots * lot_frontage < frontage_axis - 1e-6:
        notes.append(
            f"Strip leaves {frontage_axis - target_lots * lot_frontage:.1f} "
            "of unused frontage at the end (used for street tie-in or open space)."
        )
    return SubdivisionDesign(
        name=name,
        layout=LayoutKind.STRIP,
        parent=parent,
        lots=lots,
        streets=(),
        spec=lot_spec,
        notes=tuple(notes),
    )


def _build_lot(
    *,
    number: str,
    block: str,
    bbox: BBox2D,
    frontage_horizontal: bool,
    i: int,
    n: int,
    frontage_side: str,
    lot_spec: LotSpec,
) -> DesignedLot:
    crs = bbox.crs
    if frontage_horizontal:
        lot_w = bbox.width / n
        x0 = bbox.min_x + i * lot_w
        x1 = x0 + lot_w
        y0, y1 = bbox.min_y, bbox.max_y
        front_y = y0 if frontage_side == "south" else y1
        front_edge = (Point2D(x=x0, y=front_y, crs=crs), Point2D(x=x1, y=front_y, crs=crs))
        ring = (
            Point2D(x=x0, y=y0, crs=crs),
            Point2D(x=x1, y=y0, crs=crs),
            Point2D(x=x1, y=y1, crs=crs),
            Point2D(x=x0, y=y1, crs=crs),
            Point2D(x=x0, y=y0, crs=crs),
        )
        frontage = lot_w
        depth = bbox.height
    else:
        lot_h = bbox.height / n
        y0 = bbox.min_y + i * lot_h
        y1 = y0 + lot_h
        x0, x1 = bbox.min_x, bbox.max_x
        front_x = x0 if frontage_side == "west" else x1
        front_edge = (Point2D(x=front_x, y=y0, crs=crs), Point2D(x=front_x, y=y1, crs=crs))
        ring = (
            Point2D(x=x0, y=y0, crs=crs),
            Point2D(x=x1, y=y0, crs=crs),
            Point2D(x=x1, y=y1, crs=crs),
            Point2D(x=x0, y=y1, crs=crs),
            Point2D(x=x0, y=y0, crs=crs),
        )
        frontage = lot_h
        depth = bbox.width
    return DesignedLot(
        number=number,
        block=block,
        polygon=Polygon(exterior=ring),
        frontage_length=frontage,
        depth_length=depth,
        front_edge=front_edge,
        setbacks=lot_spec,
    )


# ── Layout: rectangular grid (two rows + central through-street) ───────────


def design_rectangular_grid(
    parent: Polygon,
    lot_spec: LotSpec,
    street_spec: StreetSpec,
    *,
    name: str = "Grid Subdivision",
    long_axis: str | None = None,   # "x" / "y" / None (auto)
    target_lots_per_row: int | None = None,
) -> SubdivisionDesign:
    """Two rows of lots facing each other across a central through-street.

    The street runs the full length of the parent's *long axis* (or the axis
    you pin via ``long_axis``). Lot depth is half of the perpendicular
    dimension minus half the street ROW; each lot's rear edge is the
    parent's outer boundary, each lot's front edge is the street ROW.

    Raises if the parent is too narrow to fit two depths plus the street.
    """
    bbox = parent.bbox()
    width, height = bbox.width, bbox.height

    if long_axis is None:
        long_axis = "x" if width >= height else "y"
    if long_axis not in ("x", "y"):
        raise ValueError("long_axis must be 'x' or 'y' (or None for auto).")

    long_dim = width if long_axis == "x" else height
    short_dim = height if long_axis == "x" else width
    available_depth = (short_dim - street_spec.row_width) / 2.0
    if available_depth < lot_spec.min_depth:
        raise ValueError(
            f"Parent short-axis dimension {short_dim:.1f} cannot fit two rows "
            f"of {lot_spec.min_depth:.1f}-deep lots plus a "
            f"{street_spec.row_width:.1f}-wide street."
        )

    if target_lots_per_row is None:
        target_lots_per_row = max(1, math.floor(long_dim / lot_spec.min_frontage))
        while (
            target_lots_per_row > 1
            and (long_dim / target_lots_per_row) * available_depth < lot_spec.min_area
        ):
            target_lots_per_row -= 1

    lot_frontage = long_dim / target_lots_per_row
    if lot_frontage < lot_spec.min_frontage:
        raise ValueError(
            f"Cannot fit {target_lots_per_row} lots/row along {long_dim:.1f} — "
            f"per-lot frontage {lot_frontage:.1f} < min {lot_spec.min_frontage:.1f}."
        )
    if lot_frontage * available_depth < lot_spec.min_area:
        raise ValueError(
            f"Lot would be {lot_frontage:.1f}×{available_depth:.1f} = "
            f"{lot_frontage * available_depth:.1f} < min_area {lot_spec.min_area:.1f}."
        )

    crs = bbox.crs
    lots: list[DesignedLot] = []

    if long_axis == "x":
        # Street runs left-right through y = mid.
        ymid = (bbox.min_y + bbox.max_y) / 2.0
        street_ymin = ymid - street_spec.row_width / 2.0
        street_ymax = ymid + street_spec.row_width / 2.0
        # South row (block A): facing north onto street.
        for i in range(target_lots_per_row):
            x0 = bbox.min_x + i * lot_frontage
            x1 = x0 + lot_frontage
            y0 = bbox.min_y
            y1 = street_ymin
            ring = (
                Point2D(x=x0, y=y0, crs=crs),
                Point2D(x=x1, y=y0, crs=crs),
                Point2D(x=x1, y=y1, crs=crs),
                Point2D(x=x0, y=y1, crs=crs),
                Point2D(x=x0, y=y0, crs=crs),
            )
            front_edge = (Point2D(x=x0, y=y1, crs=crs), Point2D(x=x1, y=y1, crs=crs))
            lots.append(
                DesignedLot(
                    number=str(i + 1),
                    block="A",
                    polygon=Polygon(exterior=ring),
                    frontage_length=lot_frontage,
                    depth_length=available_depth,
                    front_edge=front_edge,
                    setbacks=lot_spec,
                )
            )
        # North row (block B): facing south onto street.
        for i in range(target_lots_per_row):
            x0 = bbox.min_x + i * lot_frontage
            x1 = x0 + lot_frontage
            y0 = street_ymax
            y1 = bbox.max_y
            ring = (
                Point2D(x=x0, y=y0, crs=crs),
                Point2D(x=x1, y=y0, crs=crs),
                Point2D(x=x1, y=y1, crs=crs),
                Point2D(x=x0, y=y1, crs=crs),
                Point2D(x=x0, y=y0, crs=crs),
            )
            front_edge = (Point2D(x=x0, y=y0, crs=crs), Point2D(x=x1, y=y0, crs=crs))
            lots.append(
                DesignedLot(
                    number=str(i + 1),
                    block="B",
                    polygon=Polygon(exterior=ring),
                    frontage_length=lot_frontage,
                    depth_length=available_depth,
                    front_edge=front_edge,
                    setbacks=lot_spec,
                )
            )
        street_ring = (
            Point2D(x=bbox.min_x, y=street_ymin, crs=crs),
            Point2D(x=bbox.max_x, y=street_ymin, crs=crs),
            Point2D(x=bbox.max_x, y=street_ymax, crs=crs),
            Point2D(x=bbox.min_x, y=street_ymax, crs=crs),
            Point2D(x=bbox.min_x, y=street_ymin, crs=crs),
        )
        cl_start = Point2D(x=bbox.min_x, y=ymid, crs=crs)
        cl_end = Point2D(x=bbox.max_x, y=ymid, crs=crs)
    else:
        xmid = (bbox.min_x + bbox.max_x) / 2.0
        street_xmin = xmid - street_spec.row_width / 2.0
        street_xmax = xmid + street_spec.row_width / 2.0
        # West row (block A): facing east onto street.
        for i in range(target_lots_per_row):
            y0 = bbox.min_y + i * lot_frontage
            y1 = y0 + lot_frontage
            x0 = bbox.min_x
            x1 = street_xmin
            ring = (
                Point2D(x=x0, y=y0, crs=crs),
                Point2D(x=x1, y=y0, crs=crs),
                Point2D(x=x1, y=y1, crs=crs),
                Point2D(x=x0, y=y1, crs=crs),
                Point2D(x=x0, y=y0, crs=crs),
            )
            front_edge = (Point2D(x=x1, y=y0, crs=crs), Point2D(x=x1, y=y1, crs=crs))
            lots.append(
                DesignedLot(
                    number=str(i + 1),
                    block="A",
                    polygon=Polygon(exterior=ring),
                    frontage_length=lot_frontage,
                    depth_length=available_depth,
                    front_edge=front_edge,
                    setbacks=lot_spec,
                )
            )
        # East row (block B): facing west onto street.
        for i in range(target_lots_per_row):
            y0 = bbox.min_y + i * lot_frontage
            y1 = y0 + lot_frontage
            x0 = street_xmax
            x1 = bbox.max_x
            ring = (
                Point2D(x=x0, y=y0, crs=crs),
                Point2D(x=x1, y=y0, crs=crs),
                Point2D(x=x1, y=y1, crs=crs),
                Point2D(x=x0, y=y1, crs=crs),
                Point2D(x=x0, y=y0, crs=crs),
            )
            front_edge = (Point2D(x=x0, y=y0, crs=crs), Point2D(x=x0, y=y1, crs=crs))
            lots.append(
                DesignedLot(
                    number=str(i + 1),
                    block="B",
                    polygon=Polygon(exterior=ring),
                    frontage_length=lot_frontage,
                    depth_length=available_depth,
                    front_edge=front_edge,
                    setbacks=lot_spec,
                )
            )
        street_ring = (
            Point2D(x=street_xmin, y=bbox.min_y, crs=crs),
            Point2D(x=street_xmax, y=bbox.min_y, crs=crs),
            Point2D(x=street_xmax, y=bbox.max_y, crs=crs),
            Point2D(x=street_xmin, y=bbox.max_y, crs=crs),
            Point2D(x=street_xmin, y=bbox.min_y, crs=crs),
        )
        cl_start = Point2D(x=xmid, y=bbox.min_y, crs=crs)
        cl_end = Point2D(x=xmid, y=bbox.max_y, crs=crs)

    street_name = street_spec.name or f"{name} Drive"
    street = DesignedStreet(
        name=street_name,
        polygon=Polygon(exterior=street_ring),
        centerline_start=cl_start,
        centerline_end=cl_end,
        row_width=street_spec.row_width,
    )
    return SubdivisionDesign(
        name=name,
        layout=LayoutKind.RECTANGULAR_GRID,
        parent=parent,
        lots=tuple(lots),
        streets=(street,),
        spec=lot_spec,
    )


# ── Fabric export ───────────────────────────────────────────────────────────


def to_fabric(
    design: SubdivisionDesign, *, snap_tolerance: float = 0.05
) -> ParcelFabric:
    """Materialise a design as a :class:`ParcelFabric`.

    Lots become parcels; the central street (if any) becomes a parcel named
    ``{street}.ROW``. Shared rear/side edges are automatically welded by the
    fabric's snap-tolerant insertion.
    """
    fab = ParcelFabric(snap_tolerance=snap_tolerance)
    for lot in design.lots:
        # Drop the closing duplicate; ParcelFabric accepts open or closed rings.
        ring = list(lot.polygon.exterior[:-1])
        fab.add_parcel_from_ring(
            parcel_id=f"{lot.block}-{lot.number}",
            name=f"Block {lot.block}, Lot {lot.number}",
            ring=ring,
        )
    for street in design.streets:
        ring = list(street.polygon.exterior[:-1])
        fab.add_parcel_from_ring(
            parcel_id=f"{street.name}.ROW",
            name=f"{street.name} (right-of-way)",
            ring=ring,
        )
    return fab


# ── HTML report ─────────────────────────────────────────────────────────────


def render_html(design: SubdivisionDesign) -> str:
    """Self-contained HTML report with an SVG site plan and a lot schedule."""
    import html as _html

    bbox = design.parent.bbox()
    w = bbox.width
    h = bbox.height
    pad = max(w, h) * 0.05
    vb_w = w + 2 * pad
    vb_h = h + 2 * pad
    # SVG y-axis grows downward; flip so north is up.
    def x(p: Point2D) -> float:
        return p.x - bbox.min_x + pad

    def y(p: Point2D) -> float:
        return (bbox.max_y - p.y) + pad

    parts: list[str] = [
        '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">',
        f'<title>{_html.escape(design.name)} — site plan</title>',
        "<style>",
        "body{font-family:system-ui,sans-serif;color:#111;margin:0;padding:24px;}",
        "h1{margin:0 0 4px;}.sub{color:#666;margin:0 0 16px;font-size:14px;}",
        "svg{border:1px solid #ccc;background:#fafafa;}"
        "table{border-collapse:collapse;margin-top:16px;font-size:13px;}"
        "th,td{border:1px solid #ddd;padding:4px 8px;text-align:right;}"
        "th{background:#eee;text-align:left;}"
        ".lot{fill:#fef3c7;stroke:#b45309;stroke-width:0.4;}"
        ".lot text{fill:#7c2d12;font-size:8px;font-family:system-ui;}"
        ".street{fill:#374151;}.street-cl{stroke:#fbbf24;stroke-width:0.6;stroke-dasharray:2,2;fill:none;}"
        ".parent{fill:none;stroke:#111;stroke-width:0.8;}"
        ".issue-error{color:#b91c1c;}.issue-warning{color:#b45309;}",
        "</style></head><body>",
        f"<h1>{_html.escape(design.name)}</h1>",
        f'<p class="sub">{design.layout.value} · '
        f"{len(design.lots)} lots · "
        f"{len(design.streets)} street(s) · "
        f"parent area {design.parent.area():.0f}</p>",
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {vb_w:.2f} {vb_h:.2f}" width="700">',
    ]
    # Parent
    parts.append(_svg_polygon(design.parent, x, y, "parent"))
    # Streets
    for s in design.streets:
        parts.append(_svg_polygon(s.polygon, x, y, "street"))
        parts.append(
            f'<line class="street-cl" x1="{x(s.centerline_start):.2f}" '
            f'y1="{y(s.centerline_start):.2f}" '
            f'x2="{x(s.centerline_end):.2f}" y2="{y(s.centerline_end):.2f}"/>'
        )
    # Lots
    for lot in design.lots:
        parts.append(_svg_polygon(lot.polygon, x, y, "lot"))
        c = lot.polygon.bbox().center()
        parts.append(
            f'<text x="{x(c):.2f}" y="{y(c):.2f}" text-anchor="middle">'
            f"{_html.escape(lot.block)}-{_html.escape(lot.number)}</text>"
        )
    parts.append("</svg>")
    # Schedule
    parts.append("<h2>Lot schedule</h2><table>")
    parts.append(
        "<tr><th>Block</th><th>Lot</th><th>Frontage</th><th>Depth</th>"
        "<th>Area</th></tr>"
    )
    for lot in design.lots:
        parts.append(
            f"<tr><td>{_html.escape(lot.block)}</td><td>{_html.escape(lot.number)}</td>"
            f"<td>{lot.frontage_length:.1f}</td><td>{lot.depth_length:.1f}</td>"
            f"<td>{lot.area:.1f}</td></tr>"
        )
    parts.append("</table>")
    issues = validate_design(design)
    if issues:
        parts.append("<h2>Issues</h2><ul>")
        for i in issues:
            cls = "issue-error" if i.severity == "error" else "issue-warning"
            parts.append(
                f'<li class="{cls}">{i.severity.upper()} '
                f"(lot {_html.escape(i.lot_number or '—')}): {_html.escape(i.message)}</li>"
            )
        parts.append("</ul>")
    if design.notes:
        parts.append("<h2>Notes</h2><ul>")
        for n in design.notes:
            parts.append(f"<li>{_html.escape(n)}</li>")
        parts.append("</ul>")
    parts.append("</body></html>")
    return "".join(parts)


def _svg_polygon(poly: Polygon, x_fn, y_fn, css_class: str) -> str:
    pts = " ".join(f"{x_fn(p):.2f},{y_fn(p):.2f}" for p in poly.exterior[:-1])
    return f'<polygon class="{css_class}" points="{pts}"/>'


__all__ = [
    "DesignIssue",
    "DesignedLot",
    "DesignedStreet",
    "LayoutKind",
    "LotSpec",
    "StreetSpec",
    "SubdivisionDesign",
    "buildable_envelope",
    "design_rectangular_grid",
    "design_strip",
    "render_html",
    "to_fabric",
    "validate_design",
]
