"""DeedLM training-corpus builder.

Assembles a training corpus of (input deed text → structured JSON
target) pairs from public sources, deduplicates, splits into
train/val/test, and writes a ``parquet`` or ``jsonl`` for HuggingFace
``datasets``.

Sources (all public, attribution preserved per source):

* **BLM/GLO patents** — bulk download from glorecords.blm.gov.
* **County clerk public dumps** — varies by county; the builder accepts
  a directory of plain-text deeds and a manifest mapping each to its
  county / state.
* **Library of Congress historical deeds** — text-only OCR results.
* **Synthetic adversarial** — generated by
  :mod:`meridian.ai.deedlm.synthetic` with jurisdictional dialect knobs.

Targets are constructed by running each input through
:func:`meridian.pipelines.deed_to_polygon.parse_deed_text` and capturing
the structured output. Inputs the parser fails on are sent to a
"hard examples" pile we can hand-label later.
"""

from __future__ import annotations

import hashlib
import json
import random
from collections.abc import Iterable
from dataclasses import asdict, dataclass, field
from pathlib import Path

from meridian.pipelines.deed_to_polygon import DeedParseError, parse_deed_text


@dataclass(frozen=True, slots=True)
class CorpusEntry:
    """One (input, target) training pair."""

    id: str                    # sha-256 of normalized input
    text: str
    target_json: str
    source: str                # provenance label
    jurisdiction: str | None
    is_synthetic: bool = False


@dataclass(slots=True)
class CorpusStats:
    total_in: int = 0
    parsed_ok: int = 0
    parse_failed: int = 0
    duplicates: int = 0


@dataclass(slots=True)
class CorpusBuilder:
    """Stream inputs, parse, dedupe, and write the corpus to disk."""

    out_dir: Path
    seen_hashes: set[str] = field(default_factory=set)
    stats: CorpusStats = field(default_factory=CorpusStats)
    hard_examples: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        self.out_dir.mkdir(parents=True, exist_ok=True)

    # ── Ingest sources ──────────────────────────────────────────────────────
    def ingest_text_directory(
        self, directory: Path, *, source_label: str, jurisdiction: str | None = None
    ) -> Iterable[CorpusEntry]:
        for path in sorted(Path(directory).rglob("*.txt")):
            text = path.read_text(encoding="utf-8", errors="replace")
            entry = self._make_entry(text, source=source_label, jurisdiction=jurisdiction)
            if entry is not None:
                yield entry

    def ingest_synthetic(
        self,
        n: int,
        *,
        seed: int = 42,
        dialects: tuple[str, ...] = ("texas_vara", "ne_rod_pole", "plss_aliquot", "modern_ca"),
    ) -> Iterable[CorpusEntry]:
        from meridian.ai.deedlm.synthetic import generate_synthetic_deed

        rng = random.Random(seed)
        for _ in range(n):
            dialect = rng.choice(dialects)
            text = generate_synthetic_deed(dialect, rng=rng)
            entry = self._make_entry(text, source=f"synthetic:{dialect}", jurisdiction=None, is_synthetic=True)
            if entry is not None:
                yield entry

    # ── Internal ───────────────────────────────────────────────────────────
    def _make_entry(
        self,
        text: str,
        *,
        source: str,
        jurisdiction: str | None,
        is_synthetic: bool = False,
    ) -> CorpusEntry | None:
        normalized = " ".join(text.split())
        h = hashlib.sha256(normalized.encode("utf-8")).hexdigest()
        self.stats.total_in += 1
        if h in self.seen_hashes:
            self.stats.duplicates += 1
            return None
        self.seen_hashes.add(h)
        try:
            parsed = parse_deed_text(text)
        except DeedParseError:
            self.stats.parse_failed += 1
            self.hard_examples.append(text)
            return None
        target = {
            "calls": [
                {
                    "kind": c.kind.value,
                    "bearing_rad": c.bearing,
                    "distance_m": c.distance,
                    "radius_m": c.radius,
                    "delta_rad": c.delta,
                    "chord_m": c.chord,
                    "clockwise": c.clockwise,
                }
                for c in parsed.calls
            ],
            "point_of_beginning_text": parsed.point_of_beginning_text,
        }
        self.stats.parsed_ok += 1
        return CorpusEntry(
            id=h[:16],
            text=text,
            target_json=json.dumps(target, sort_keys=True, separators=(",", ":")),
            source=source,
            jurisdiction=jurisdiction,
            is_synthetic=is_synthetic,
        )

    # ── Output ─────────────────────────────────────────────────────────────
    def write_jsonl(
        self,
        entries: Iterable[CorpusEntry],
        *,
        train_ratio: float = 0.85,
        val_ratio: float = 0.10,
        seed: int = 0,
    ) -> dict[str, Path]:
        """Split entries deterministically and write three jsonl files.

        Returns the paths to the train/val/test files.
        """
        all_entries = list(entries)
        rng = random.Random(seed)
        rng.shuffle(all_entries)
        n = len(all_entries)
        train_n = int(n * train_ratio)
        val_n = int(n * val_ratio)
        splits = {
            "train": all_entries[:train_n],
            "val": all_entries[train_n : train_n + val_n],
            "test": all_entries[train_n + val_n :],
        }
        paths: dict[str, Path] = {}
        for split_name, items in splits.items():
            p = self.out_dir / f"{split_name}.jsonl"
            with p.open("w", encoding="utf-8") as f:
                for e in items:
                    f.write(json.dumps(asdict(e), ensure_ascii=False) + "\n")
            paths[split_name] = p
        # Hard examples for hand-labelling.
        hard_path = self.out_dir / "hard_examples.txt"
        hard_path.write_text("\n\n--- HARD ---\n\n".join(self.hard_examples), encoding="utf-8")
        return paths
